### ISSUE TITLE
Map.forEach: callback arguments flipped

### ISSUE THREAD

**Issue by afandria** [WebReflection/es6-collections#18]
ES6 Specification: [Map.forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach)

The argument order for the callback should be (value, key, obj), but the tests have the order as (key, value, obj). The issue seems to be the implementation of [sharedForEach](https://github.com/WebReflection/es6-collections/blob/master/index.js#L187), which has the incorrect order.

**Comment by anywhichway** [comment]
I assume this is still an issue because:

1) It is not marked closed
2) I downloaded and started using the code today and am experiencing the same problem.

Meanwhile, for anyone else coming across this bug below is a shimy-shim to put right after you load es6-collections.

`Map.prototype._forEach = Map.prototype.forEach;
	Map.prototype.forEach = function(f) { this._forEach(function(key,value,object) { f(value,key,object); }); }`

**Comment by WebReflection** [comment]
I think you are correct, never pushed or published to npm the change. Do you mind verifying everything is now OK? Thanks!

**Comment by anywhichway** [comment]
Seems to be working! Thanks.
