### ISSUE TITLE
keys/values/entries should return Iterator not Array

### ISSUE THREAD

**Issue by infinity0** [WebReflection/es6-collections#22]
For example, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/values

An iterator is just an object with a next() method, as per:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/The_Iterator_protocol

**Comment by WebReflection** [comment]
the Iterator "burden" won't probably ever land in here ... have a look at https://github.com/paulmillr/es6-shim/

**Comment by infinity0** [comment]
It's quite ridiculous to say that, yet try to pretend that this is a "shim" for ES6 collections. A shim follows the standards, there is no negotiation - otherwise it's not a "shim" but a "fork".

The main reason I choose this library is because of its small size. es6-shim is many times larger. I don't think it's much of an effort to implement the iterator protocol. Would you accept a pull request?

**Comment by WebReflection** [comment]
so this was born on Jan 17, 2012 when standards where not even defined yet. It wasn't ridiculous at that time because it was respecting drafts closely and Iterator wasn't even there.

Things changed in the meanwhile and became more complex to follow from a collection only point of view, because of the nature of the Iterator that should not break or affect everything else (but it does, that is why if you need the iterator you need to fix much more than collections)

I don't want duplicate es6-shim project and the moment you'll implement Iterator, Object.is, and all whatever you need to make it work properly, the size, the reason you are here, won't be that small anymore.

I rather deprecate this module instead: who's being using it for the last 3 years will be just fine, newcomers like you that want full shim (which is impossible, just read about the WeakMap issue, as example) and small size (which is not small anymore once this becomes a full shim) will be redirected to a way more actively maintained project.

How ridiculous does *this* sound?

**Comment by infinity0** [comment]
There is not *that* much towards being a full shim.

~~~~
values = function() {
  var i = 0, self = this;
  return {
    next: function() {
      return (i < self._values.length)? { done: false, result: self._values[i++]}: { done: true };
    }
  };
}
~~~~

**Comment by WebReflection** [comment]
would that work out o the box and will avoid xonflicts with any library or piece of code that deal with real Iterators ? 'cause I remember it wasn't that simple to put it in, I remember es6-shim does much more than just that (IIRC)

**Comment by infinity0** [comment]
Probably yes it would work out of the box. I don't know what es6-shim does, but I imagine it also has a different internal representation of the data structure, so what I did may not be directly applicable. Also if you have any specific issues in mind, I can try to address them.

**Comment by WebReflection** [comment]
I don't actually know if you do not address the iterator if that would break somehow.
As example, you get `var itr = map.keys()` and then you `itr.next()` ... would any other part of the code that gets `map.keys()` return same iterator or not?

If this is not a concern then feel free to PR updating tests too. I will bump everything here since it's even more breaking change than the other ^_^

**Comment by infinity0** [comment]
Every time you call keys()/values() etc yes, a new iterator should be returned that starts from the beginning with i=0. OK, I will work on adding some tests. It will take a while longer though. :)

**Comment by infinity0** [comment]
Although, there is the question of what should happen if the data changes *during* the iteration. I will look up the specs for that. Maybe this is the tricky thing that might bloat the code, we will see...

**Comment by WebReflection** [comment]
thanks
